[package]
name = "tavern_roll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tavern_die = { git = "https://github.com/lcleveland/tavern_die" }
